export const CREATED_PROVIDER = 'CREATED_PROVIDER';
export const ERROR_CREATE_PROVIDER = 'ERROR_CREATE_PROVIDER';
export const GET_PROVIDER = 'GET_PROVIDER';
export const ERROR_GET_PROVIDER = 'ERROR_GET_PROVIDER';
export const GET_PROVIDERS = 'GET_PROVIDERS';
export const ERROR_GET_PROVIDERS = 'ERROR_GET_PROVIDERS';
export const UPDATED_PROVIDER = 'UPDATED_PROVIDER';
export const ERROR_UPDATE_PROVIDER = 'ERROR_UPDATE_PROVIDER';
export const DELETED_PROVIDER = 'DELETED_PROVIDER';
export const ERROR_DELETE_PROVIDER = 'ERROR_DELETE_PROVIDER';
export const CLEAN_PROVIDER_STATE = 'CLEAN_PROVIDER_STATE';
export const SEARCHED_PROVIDER = 'SEARCHED_PROVIDER';
export const ERROR_SEARCHED_PROVIDER = 'ERROR_SEARCHED_PROVIDER';


export const CREATED_PRODUCT = 'CREATE_PRODUCT';
export const ERROR_CREATED_PRODUCT = 'ERROR_CREATED_PRODUCT';
export const GET_PROVIDER_PRODUCTS = 'GET_PROVIDER_PRODUCTS';
export const ERROR_GET_PROVIDER_PRODUCTS = 'GET_PROVIDER_PRODUCTS';
export const UPDATED_PRODUCT = 'UPDATE_PRODUCT';
export const ERROR_UPDATED_PRODUCT = 'ERROR_UPDATED_PRODUCT';
export const DELETED_PRODUCT = 'DELETED_PRODUCT';
export const ERROR_DELETE_PRODUCT = 'ERROR_DELETE_PRODUCT';
export const CLEAN_PRODUCT_STATE = 'CLEAN_PRODUCT_STATE';


export const SET_SEARCH_TEXT = 'SET_SEARCH_TEXT';