export const CHANGE_PROVIDER_FORM_NAME = 'CHANGE_PROVIDER_NAME_FORM';
export const CHANGE_PROVIDER_FORM_CNPJ = 'CHANGE_PROVIDER_FORM_CNPJ';
export const CHANGE_PROVIDER_FORM_FONE = 'CHANGE_PROVIDER_FORM_FONE';
export const CHANGE_PROVIDER_FORM_ADDRESS = 'CHANGE_PROVIDER_FORM_ADDRESS';
export const CREATED_PROVIDER = 'CREATED_PROVIDER';
export const ERROR_CREATE_PROVIDER = 'ERROR_CREATE_PROVIDER';
export const GET_PROVIDER_VIEW = 'GET_PROVIDER_VIEW';
export const ERROR_GET_PROVIDER = 'ERROR_GET_PROVIDER';
export const GET_PROVIDERS = 'GET_PROVIDERS';
export const ERROR_GET_PROVIDERS = 'ERROR_GET_PROVIDERS';
export const GET_PROVIDER_EDIT = 'GET_PROVIDER_EDIT';
export const UPDATED_PROVIDER = 'UPDATED_PROVIDER';
export const ERROR_UPDATE_PROVIDER = 'ERROR_UPDATE_PROVIDER';
export const DELETED_PROVIDER = 'DELETED_PROVIDER';
export const ERROR_DELETE_PROVIDER = 'ERROR_DELETE_PROVIDER';
export const CLEAN_PROVIDER_STATE = 'CLEAN_PROVIDER_STATE';
export const CLEAN_PROVIDER_FORM = 'CLEAN_PROVIDER_FORM';
export const CLEAN_PROVIDER_FORM_FEEDBACK_MESSAGE = 'CLEAN_PROVIDER_FORM_FEEDBACK_MESSAGE';
export const SEARCHED_PROVIDER = 'SEARCHED_PROVIDER';
export const ERROR_SEARCHED_PROVIDER = 'ERROR_SEARCHED_PROVIDER';


export const CREATED_PRODUCT = 'CREATE_PRODUCT';
export const ERROR_CREATED_PRODUCT = 'ERROR_CREATED_PRODUCT';
export const GET_PROVIDER_PRODUCTS = 'GET_PROVIDER_PRODUCTS';
export const ERROR_GET_PROVIDER_PRODUCTS = 'GET_PROVIDER_PRODUCTS';
export const UPDATED_PRODUCT = 'UPDATE_PRODUCT';
export const ERROR_UPDATED_PRODUCT = 'ERROR_UPDATED_PRODUCT';
export const DELETED_PRODUCT = 'DELETED_PRODUCT';
export const ERROR_DELETE_PRODUCT = 'ERROR_DELETE_PRODUCT';
export const CLEAN_PRODUCT_STATE = 'CLEAN_PRODUCT_STATE';


export const SET_SEARCH_TEXT = 'SET_SEARCH_TEXT';